---
title: TypeError 'buildid' is an invalid keyword argument for this function
---

# TypeError: 'buildid' is an invalid keyword argument for this function

<p>使用django 保存对象的时候，报了如下错误，大概意思是字段是无效的：</p><p style="text-align: center;"><br/></p><p style="text-align: center;"><br/></p><p style="text-align: center;"><img src="https://oss.88cto.com/hQaBe2Pw.png" title="" alt="hQaBe2Pw.png" width="914" height="141" style="width: 914px; height: 141px;"/></p><pre class="brush:plain;toolbar:false">Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
&nbsp;&nbsp;File&nbsp;&quot;/Users/panjing/dev/qikenet/qikenet/tests.py&quot;,&nbsp;line&nbsp;67,&nbsp;in&nbsp;test_firmware
&nbsp;&nbsp;&nbsp;&nbsp;signed=f[&#39;signed&#39;]
&nbsp;&nbsp;File&nbsp;&quot;/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/manager.py&quot;,&nbsp;line&nbsp;82,&nbsp;in&nbsp;manager_method
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;getattr(self.get_queryset(),&nbsp;name)(*args,&nbsp;**kwargs)
&nbsp;&nbsp;File&nbsp;&quot;/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/query.py&quot;,&nbsp;line&nbsp;411,&nbsp;in&nbsp;create
&nbsp;&nbsp;&nbsp;&nbsp;obj&nbsp;=&nbsp;self.model(**kwargs)
&nbsp;&nbsp;File&nbsp;&quot;/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/base.py&quot;,&nbsp;line&nbsp;485,&nbsp;in&nbsp;__init__
&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;TypeError(&quot;&#39;%s&#39;&nbsp;is&nbsp;an&nbsp;invalid&nbsp;keyword&nbsp;argument&nbsp;for&nbsp;this&nbsp;function&quot;&nbsp;%&nbsp;kwarg)
TypeError:&nbsp;&#39;buildid&#39;&nbsp;is&nbsp;an&nbsp;invalid&nbsp;keyword&nbsp;argument&nbsp;for&nbsp;this&nbsp;function
----------------------------------------------------------------------</pre><p>以为是字段没有加上去，然后排查模型</p><p style="text-align: center;"><img src="https://oss.88cto.com/pqhK9WPm.png" width="100%" title="" alt="pqhK9WPm.png"/></p><p>有这个字段，然后排查数据库</p><p style="text-align: center;"><img src="https://oss.88cto.com/iMUdYupt.png" width="100%" title="" alt="iMUdYupt.png"/></p><p><br/></p><p>用迁移命令重新生成</p><pre class="brush:bash;toolbar:false">&nbsp;python3&nbsp;manage.py&nbsp;makemigrations
No&nbsp;changes&nbsp;detected</pre><p>检测不到这个字段，只能手动去加一下了，或者删除django的迁移日志，整个表重新生成。</p><p>迁移日志在django_migrations表中。</p>



